mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('register.urls', namespace="auth")),
    url(r'^', include('post.urls', namespace="post")),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from .views import AllPostView, PostByTags, UserPostListView, PostCreateView

urlpatterns = [

    # url(r'^$', views.post_list, name='home'),
    url(r'^$', AllPostView.as_view(), name='home'),
    url(r'^create/$', PostCreateView.as_view(), name='post_create'),
    # url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<id>\d+)/addcomment/$', views.add_comment, name='add_comment'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update, name='edit_post'),
    url(r'^user_list/$', views.users_list, name='users_list'),
    # url(r'^(?P<id>\d+)/user_post_list/$', views.user_post_list, name='user_post_list'),
    url(r'^(?P<id>\d+)/user_post_list/$',UserPostListView.as_view(), name= 'user_post_list'),
    url(r'^(?P<id>\d+)/user_comments_list/$', views.user_comments_list, name='user_comments_list'),
    # url(r'^post_by_tags/(?P<tag>[-\w]+)/$', views.post_by_tags, name='post_by_tags'),
    url(r'^post_by_tags/(?P<tag>[-\w]+)/$', PostByTags.as_view(), name='post_by_tags'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete_post'),


]

register/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^logout/', views.log_out, name='logout'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<id>\d+)/view_profile/$', views.view_profile, name='view_profile'),
    url(r'^(?P<id>\d+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<id>\d+)/password/$', views.password_change, name='password_change'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),


]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# from django.utils import timezone
from taggit.managers import TaggableManager


def upload_location(instance, filename):
    return '{}/{}'.format(instance.id, filename)


class Post(models.Model):

    title = models.CharField(max_length=120)
    content = models.TextField()
    user = models.ForeignKey(User)
    image = models.ImageField(upload_to=upload_location, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    date_created = models.DateTimeField(auto_now_add=True)
    views_count = models.IntegerField(blank=True, default=0)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', kwargs={"id": self.id})


class Comment(models.Model):

    comment_text = models.TextField()
    post_to = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_left = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text

post/forms.py
from django.forms import ModelForm
from .models import Comment, Post, User


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields =[
            'comment_text',
        ]


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'tags',
            'image',
        ]


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',

        ]

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView
# from . import filters
from .filters import PostFilter
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import CommentForm, PostForm
# Create your views here.


class AllPostView(ListView):

    template_name = 'home_page.html'
    model = Post
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.all().order_by("-date_created")

    def get_context_data(self, **kwargs):

        context = super(AllPostView, self).get_context_data(**kwargs)
        username = None
        if self.request.user.is_staff\
            or self.request.user.is_superuser\
                or self.request.user.is_authenticated:
            username = auth.get_user(self.request).username

        page_request_var = 'page'

        context['username'] = username
        context['page_request_var'] = page_request_var
        return context


# def post_list(request):
#     username = None
#     if request.user.is_staff or request.user.is_superuser or request.user.is_authenticated:
#         username = auth.get_user(request).username
#
#     query_post_list = Post.objects.all().order_by("-date_created")
#     paginator = Paginator(query_post_list, 10)  # Show 10  per page
#     page_request_var = 'page'
#     page = request.GET.get(page_request_var)
#
#     try:
#         queryset = paginator.page(page)
#     except PageNotAnInteger:
#         queryset = paginator.page(1)
#     except EmptyPage:
#         queryset = paginator.page(paginator.num_pages)
#
#     context = {
#         'post_list': queryset,
#         'username': username,
#         'page_request_var': page_request_var,
#     }
#     return render(request, 'home_page.html', context)

class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'post_creation_form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        form.save_m2m()
        return redirect(instance.get_absolute_url())

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context

    def form_invalid(self, form):
        return redirect('post: post_create')

# def post_create(request):
#     user = request.user
#     form = PostForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         instance = form.save(commit=False)
#         instance.user = User.objects.get(id=user.pk)
#         instance.save()
#         form.save_m2m()
#         return HttpResponseRedirect(instance.get_absolute_url())
#     context = {
#         "form": form,
#         'username': auth.get_user(request).username,
#     }
#     return render(request, 'post_creation_form.html', context)


def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    user = request.user
    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username
    else:
        username = None

    if instance.user_id == user.pk:
        if request.POST:
            form = PostForm(request.POST or None,
                            request.FILES or None, instance=instance)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                form.save_m2m()
                return HttpResponseRedirect(instance.get_absolute_url())
            else:
                return redirect('post:edit_post', id=id)
        else:
            form = PostForm(instance=instance)
            context = {
                "instance": instance,
                "form": form,
                'username': username,
            }
        return render(request, 'post_creation_form.html', context)
    else:
        return redirect('post:home')


def post_detail(request, id):
    post_instance = get_object_or_404(Post, id=id)
    comment_instance = Comment.objects.filter(post_to_id=id)
    user = request.user
    comment_form = None
    username = None
    tag_form = None
    can_edit = None
    can_delete = None

    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username
        comment_form = CommentForm()

    if post_instance.user_id == user.pk:
        can_edit = True
        can_delete = True
    else:
        post_instance.views_count += 1

    post_instance.save()

    context = {
        'post_instance': post_instance,
        'comment_instance': comment_instance,
        'form': comment_form,
        'username': username,
        'tag_form': tag_form,
        'can_edit': can_edit,
        'can_delete': can_delete,
    }
    return render(request, 'post_detail.html', context)


def add_comment(request, id):
    post = get_object_or_404(Post, id=id)
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            user = request.user
            comment = form.save(commit=False)
            comment.post_to = Post.objects.get(id=id)
            comment.user_left = User.objects.get(id=user.pk)
            form.save()
    return redirect(post.get_absolute_url())


class PostByTags(AllPostView):
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['tag']).order_by("-date_created")

# def post_by_tags(request, tag):
#     username = None
#     if request.user.is_staff or request.user.is_superuser or request.user.is_authenticated:
#         username = auth.get_user(request).username
#
#     query_post_list = Post.objects.filter(tags__slug=tag).order_by("-date_created")
#     paginator = Paginator(query_post_list, 10)  # Show 10  per page
#     page_request_var = 'page'
#     page = request.GET.get(page_request_var)
#
#     try:
#         queryset = paginator.page(page)
#     except PageNotAnInteger:
#         queryset = paginator.page(1)
#     except EmptyPage:
#         queryset = paginator.page(paginator.num_pages)
#
#     context = {
#         'post_list': queryset,
#         'username': username,
#         'page_request_var': page_request_var,
#     }
#     return render(request, 'home_page.html', context)


def users_list(request):
    users_lists = User.objects.all()
    context = {
        'users': users_lists,
        'username': auth.get_user(request).username,
    }
    return render(request, 'users_list.html', context)


class UserPostListView(AllPostView):
    paginate_by = 10

    def get_queryset(self):
        queryset = PostFilter(self.request.GET,
                              queryset=Post.objects.
                              filter(user_id=self.kwargs['id']).
                              order_by("-date_created"))
        return queryset.qs

    def get_context_data(self, **kwargs):
        context = super(UserPostListView, self).get_context_data(**kwargs)
        model_filtered = PostFilter(self.request.GET,
                                    queryset=Post.objects.
                                    filter(user_id=self.kwargs['id']).
                                    order_by("-date_created"))
        context['filter'] = model_filtered
        return context


# def user_post_list(request, id):
#
#     username = None
#     if request.user.is_staff or request.user.is_superuser or request.user.is_authenticated:
#         username = auth.get_user(request).username
#
#     post_filtered = PostFilter(
#         request.GET,
#         queryset=Post.objects.filter(user_id=id).order_by("-date_created")
#     )
#
#     paginator = Paginator(post_filtered.qs, 5)  # Show 10  per page
#     page_request_var = 'page'
#     page = request.GET.get(page_request_var)
#
#     try:
#         queryset = paginator.page(page)
#     except PageNotAnInteger:
#         queryset = paginator.page(1)
#     except EmptyPage:
#         queryset = paginator.page(paginator.num_pages)
#
#     context = {
#         'filter': post_filtered,
#         'post_list': queryset,
#         'username': username,
#         'page_request_var': page_request_var,
#     }
#     return render(request, 'home_page.html', context)


def user_comments_list(request, id):
    comments_list = Comment.objects.filter(user_left_id=id)
    post_list = Post.objects.filter(user_id=id)
    context = {
        'posts': post_list,
        'comments': comments_list,
        'username': auth.get_user(request).username,
    }
    return render(request, 'comments_list.html', context)


def post_delete(request, id):
    instance = get_object_or_404(Post, id=id)
    user = request.user
    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username
    else:
        username = None
    if instance.user_id == user.pk:
        if request.POST:
            Post.objects.get(id=id).delete()
            return redirect('/')
        else:
            context = {
                'post': instance,
                'username': username,
            }
            return render(request, 'post_delete_form.html', context)
    else:
        return redirect('post:home')

post/templates/base.html
{% load static from staticfiles %}


<!--<!DOCTYPE html>-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock title %} Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href='{% static "style.css" %}' rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           {% if username %}
          <a class="navbar-brand" href='{% url "auth:my_profile" %}'>My Profile</a>
            {% endif %}
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li><a href='{% url "post:home" %}'>Home</a></li>

                {% if username %}
            <li><a href='{% url "post:post_create" %} '>Create post</a></li>
                {% endif %}
            <li><a href='{% url "post:users_list" %}'>Users list</a></li>

                {% if username %}
                <li><a href='{% url "auth:logout"%}'>Log out "{{username}}"</a></li>
                {% else %}
                <li><a href='{% url "auth:login"%}'>log In</a></li>
                {% endif %}

              </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container main_content">

        {% block content %}
        {% endblock content %}

      {% block login %}
      {% endblock login %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

post/templates/comments_list.html
{% extends 'base.html' %}

{% block content %}
   <!--Post :  {{ comment.post_to }}-->

    {% for comment in comments %}
            <p>
            <strong>Post :</strong> {{ comment.post_to }}
            <strong>comment :</strong> {{ comment.comment_text }}
            </p>
            <hr>

        {% empty %}
        <h3>No comments found</h3>
    {% endfor %}


<!--{% for comment in comments %}-->
<!--{% endfor %}-->
{% endblock content %}

post/templates/detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}
{{ post_instance.title }}
{% endblock title %}
{% block content %}


<h1>{{ post_instance.title }}</h1>
<h4>created :{{post_instance.date_created }}</h4>

{% if post_instance.updated != post_instance.date_created%}
<h4>updated :{{post_instance.updated }}</h4>
{% endif%}

 {% if post_instance.image %}
    <img src='{{ post_instance.image.url }}' class='img-responsive' width="400px" height="400px">
    {% endif %}

<p>{{ post_instance.content|linebreaks }}</p>
<p><img src="{% static 'eye.jpg' %}" width="20px" height="20px"> {{ post_instance.views_count }}</p>

<h4>author : <a href='{% url "auth:view_profile" post_instance.user.id %}'>{{ post_instance.user }}</a></h4>

    {% if can_edit %}
<p> <button type="button" class="btn btn-default" value="Edit"><a href="{% url 'post:edit' post_instance.id %}">Edit Post</a> </button></p>
    {% endif %}

{% if can_delete %}
 <button type="button" class="btn btn-default" value="Delete post"><a href="{% url 'post:delete' post_instance.id %}">Delete Post</a> </button>
    {% endif %}


<div class="comments">
    {% if comment_instance %}
<h2>Comments</h2>
        <hr>
    {% for com in comment_instance %}
        <p>{{ com.created }}</p>
        <p>user left :{{ com.user_left }}</p>
        <p>{{ com.comment_text }}</p>
        <hr>
    {% endfor %}
    {% endif %}
    {% if form %}
        <form method="POST" enctype="multipart/form-data" action="{% url 'post:comment' post_instance.id %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-default" value="Add comment" size="small">
        </form>
    {% endif %}
</div>

{% endblock content %}

post/templates/home.html
{% extends "base.html" %}

{% block title %}
HOME
{% endblock title %}

{% block content %}

 {% if filter %}
  <form action='' method="get">
      <h3>  Filter by date</h3>
    {{ filter.form.as_table }}
    <button type="submit">Search</button>
  </form>
    {% endif %}


    {% if post_list %}
            {% for post in post_list %}
                <h3><a href='{{ post.get_absolute_url }}'>{{ post.title}}</a></h3>
                <h3>{{ post.date_created }}</h3>

                    {% if post.image %}
                        <img src='{{ post.image.url }}' class='img-responsive' width="400px" height="400px" >
                    {% endif %}
                <p>{{ post.content|linebreaks|truncatechars:50 }}</p>

                        {% with tags=post.tags.slugs %}
                        {% if tags.count > 0 %}
                <p>Tags:
                {% for tag in tags %}
                    {% if not forloop.first %} {% endif %}
                    <a href=" {% url 'post:tags' tag %}  ">{{ tag }}</a>
                {% endfor %}
                    </p>
                     {% endif %}
                        {% endwith %}


                <p>author: {{ post.user }} </p>
                <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                <hr>
            {% endfor %}
        {% else %}
        <h3>No posts found</h3>
    {% endif %}



<div class="pagination">
    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?{{ page_request_var }}={{ post_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
        </span>

        {% if post_list.has_next %}
            <a href="?{{ page_request_var }}={{ post_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

post/templates/home_page.html
{% extends "base.html" %}

{% block title %}
HOME
{% endblock title %}

{% block content %}

 {% if filter %}
  <form action='' method="get">
      <h3>  Filter by date</h3>
    {{ filter.form.as_table }}
    <button type="submit">Search</button>
  </form>
    {% endif %}



        {% for post in post_list %}
                <h3><a href='{{ post.get_absolute_url }}'>{{ post.title}}</a></h3>
                <h3>{{ post.date_created }}</h3>

                    {% if post.image %}
                        <img src='{{ post.image.url }}' class='img-responsive' width="400px" height="400px" >
                    {% endif %}
                <p>{{ post.content|linebreaks|truncatechars:50 }}</p>

                        {% with tags=post.tags.slugs %}
                        {% if tags.count > 0 %}
                <p>Tags:
                {% for tag in tags %}
                    {% if not forloop.first %} {% endif %}
                    <a href=" {% url 'post:post_by_tags' tag %}  ">{{ tag }}</a>
                {% endfor %}
                    </p>
                     {% endif %}
                        {% endwith %}

                <p>author: {{ post.user }} </p>
                <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                <hr>

            {% empty %}
            <h3>No posts found</h3>
        {% endfor %}


<!--{% if is_paginated %}-->
  <!--<ul class="pagination">-->
    <!--{% if page_obj.has_previous %}-->
      <!--<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>-->
    <!--{% else %}-->
      <!--<li class="disabled"><span>&laquo;</span></li>-->
    <!--{% endif %}-->
    <!--{% for i in paginator.page_range %}-->
      <!--{% if page_obj.number == i %}-->
        <!--<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>-->
      <!--{% else %}-->
        <!--<li><a href="?page={{ i }}">{{ i }}</a></li>-->
      <!--{% endif %}-->
    <!--{% endfor %}-->
    <!--{% if page_obj.has_next %}-->
      <!--<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>-->
    <!--{% else %}-->
      <!--<li class="disabled"><span>&raquo;</span></li>-->
    <!--{% endif %}-->
  <!--</ul>-->
<!--{% endif %}-->


{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{{ page_request_var }}={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endif %}
{% endblock content %}

post/templates/post_creation_form.html
{% extends "base.html" %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Post Form</h1>
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" class='btn btn-default' value="Create post" />
    </form>
    </div>
{% endblock content %}

post/templates/post_delete_form.html
{% extends "base.html" %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Delete Post</h1>
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        <h2>{{ post.title }}</h2>
        <h4>created :{{post.date_created }}</h4>
             {% if post.image %}
        <img src='{{ post.image.url }}' class='img-responsive' width="400px" height="400px">
        {% endif %}
        <p>{{ post.content|linebreaks }}</p>
    <input type="submit" class='btn btn-default' value="Delete post" />
    </form>
    </div>
{% endblock content %}

post/templates/post_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}
{{ post_instance.title }}
{% endblock title %}
{% block content %}


<h1>{{ post_instance.title }}</h1>
<h4>created :{{post_instance.date_created }}</h4>


 {% if post_instance.image %}
    <img src='{{ post_instance.image.url }}' class='img-responsive' width="400px" height="400px">
    {% endif %}

<p>{{ post_instance.content|linebreaks }}</p>
<p><img src="{% static 'eye.jpg' %}" width="20px" height="20px"> {{ post_instance.views_count }}</p>

<h4>author : <a href='{% url "auth:view_profile" post_instance.user.id %}'>{{ post_instance.user }}</a></h4>

    {% if can_edit %}
<p> <button type="button" class="btn btn-default" value="Edit"><a href="{% url 'post:edit_post' post_instance.id %}">Edit Post</a> </button></p>
    {% endif %}

{% if can_delete %}
 <button type="button" class="btn btn-default" value="Delete post"><a href="{% url 'post:delete_post' post_instance.id %}">Delete Post</a> </button>
    {% endif %}


<div class="comments">
    {% if comment_instance %}
<h2>Comments</h2>
        <hr>
    {% for com in comment_instance %}
        <p>{{ com.created }}</p>
        <p>user left :{{ com.user_left }}</p>
        <p>{{ com.comment_text }}</p>
        <hr>
    {% endfor %}
    {% endif %}
    {% if form %}
        <form method="POST" enctype="multipart/form-data" action="{% url 'post:add_comment' post_instance.id %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-default" value="Add comment" size="small">
        </form>
    {% endif %}
</div>

{% endblock content %}

post/templates/post_form.html
{% extends "base.html" %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Post Form</h1>
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" class='btn btn-default' value="Create post" />
    </form>
    </div>
{% endblock content %}

post/templates/users_list.html
{% extends 'base.html' %}

{% block content %}
    {% for user in users %}
        <h4>User : <a href='{% url "auth:view_profile" user.id %}'>{{ user }}</a></h4>
         <a href='{% url "post:user_post_list" user.id %} '>Posts</a>
        <br>
        <a href='{% url "post:user_comments_list" user.id%}'> Comments</a>
        <hr>
        {% empty %}
           <h4>No Users found</h4>
    {% endfor %}

{% endblock content %}