mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('register.urls', namespace="auth")),
    url(r'^', include('post.urls', namespace="post")),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from .views import AllPostView, PostByTags, UserPostListView, PostCreateView

urlpatterns = [

    # url(r'^$', views.post_list, name='home'),
    url(r'^$', AllPostView.as_view(), name='home'),
    url(r'^create/$', PostCreateView.as_view(), name='post_create'),
    # url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<id>\d+)/addcomment/$', views.add_comment, name='add_comment'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update, name='edit_post'),
    url(r'^user_list/$', views.users_list, name='users_list'),
    # url(r'^(?P<id>\d+)/user_post_list/$', views.user_post_list, name='user_post_list'),
    url(r'^(?P<id>\d+)/user_post_list/$',UserPostListView.as_view(), name= 'user_post_list'),
    url(r'^(?P<id>\d+)/user_comments_list/$', views.user_comments_list, name='user_comments_list'),
    # url(r'^post_by_tags/(?P<tag>[-\w]+)/$', views.post_by_tags, name='post_by_tags'),
    url(r'^post_by_tags/(?P<tag>[-\w]+)/$', PostByTags.as_view(), name='post_by_tags'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete_post'),


]

register/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^logout/', views.log_out, name='logout'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<id>\d+)/view_profile/$', views.view_profile, name='view_profile'),
    url(r'^(?P<id>\d+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<id>\d+)/password/$', views.password_change, name='password_change'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),


]

register/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


def upload_location(instance, filename):
    return '{}/{}'.format(instance.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.TextField(null=True, blank=True,)
    birth_date = models.DateField(
        null=True,
        blank=True,
        help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    photo = models.ImageField(upload_to=upload_location, blank=True, null=True)
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

register/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]


class ProfileForm(forms.ModelForm):
    telephone = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = Profile
        fields = [
            'telephone',
            'birth_date',
            'country',
            'photo',

        ]


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = {
            'password',
            'email',
            'first_name',
            'last_name',
        }

register/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm)
from .forms import RegistrationForm, ProfileForm, EditProfileForm
from .models import Profile
from django.shortcuts import get_object_or_404
# Create your views here.


def log_in(request):
    context = {
        'form': AuthenticationForm(),
    }

    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('post:home')
        else:
            context = {
                'error': 'user not found',
            }
            return render(request, 'login.html', context)
    else:
        return render(request, 'login.html', context)


def log_out(request):
    auth.logout(request)
    return redirect('post:home')


def register(request):

    if request.POST:
        newuser_form = RegistrationForm(request.POST or None)
        profile_form = ProfileForm(request.POST or None, request.FILES or None)

        if newuser_form.is_valid() and profile_form.is_valid():

            newuser_form.save()
            newuser = auth.authenticate(
                username=newuser_form.cleaned_data['username'],
                password=newuser_form.cleaned_data['password1'], )

            auth.login(request, newuser)
            profile = profile_form.save(commit=False)
            profile.user = User.objects.get(id=newuser.id)
            profile.save()
            return redirect('post:home')
        else:
            return redirect('post:users_list')
    else:
        context = {
            'user_form': RegistrationForm(),
            'profile_form': ProfileForm(),
        }
        return render(request, 'register.html', context)


def view_profile(request, id):
    user_instance = get_object_or_404(User, id=id)
    username = None
    can_edit = None
    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username

    if user_instance.id == request.user.id:
        can_edit = True

    context = {
        'user': user_instance,
        'can_edit': can_edit,
        'username': username,
    }

    return render(request, 'profile.html', context)


def edit_profile(request, id):
    user_instance = get_object_or_404(User, id=id)
    profile_instance = user_instance.profile
    user = request.user

    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username

        if user_instance.id == user.pk:
            if request.POST:

                user_form = EditProfileForm(request.POST, instance=user_instance)
                profile_form = ProfileForm(request.POST or None,
                                           request.FILES or None,
                                           instance=profile_instance)
                if user_form.is_valid() and profile_form.is_valid():
                    user_form.save()
                    profile_form.save()

                    return redirect('auth:view_profile', id=request.user.id)
                else:
                    return redirect('auth:edit_profile', id=request.user.id)
            else:
                user_form = EditProfileForm(instance=request.user)
                profile_form = ProfileForm(instance=request.user.profile)
                context = {
                    'user_form': user_form,
                    'profile_form': profile_form,
                    'username': username,
                }
            return render(request, 'edit_profile.html', context)
        else:
            return redirect('auth:my_profile')
    else:
        return redirect('post:home')


def password_change(request, id):
    user_instance = get_object_or_404(User, id=id)
    user = request.user
    username = None
    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username

        if user_instance.id == user.pk:

            if request.POST:
                form = PasswordChangeForm(data=request.POST, user=request.user)

                if form.is_valid():
                    form.save()
                    update_session_auth_hash(request, form.user)
                    return redirect('auth:view_profile', id=request.user.id)

            else:
                form = PasswordChangeForm(user=request.user)
                context = {
                    'form': form,
                    'username': username
                }
                return render(request, 'change_password.html', context)
        else:
            return redirect('auth:my_profile')
    else:
        return redirect('post:home')


def my_profile(request):
    user_instance = get_object_or_404(User, id=auth.get_user(request).id)

    username = None
    can_edit = None
    if request.user.is_staff or\
            request.user.is_superuser or\
            request.user.is_authenticated:
        username = auth.get_user(request).username

    if user_instance.id == request.user.id:
        can_edit = True

    context = {
        'user': user_instance,
        'can_edit': can_edit,
        'username': username,
    }

    return render(request, 'profile.html', context)

register/templates/change_password.html
{% extends 'base.html' %}

{% block login %}

<div class="form-group">
        <form  method="POST" >
            {% csrf_token %}

            {{ form.as_p }}
            <p><input class="button" type="submit" value="Edit">

        </form>
</div>

{% endblock login %}

register/templates/edit_profile.html
{% extends 'base.html' %}

{% block login %}

<div class="form-group">
        <form action='{% url "auth:edit_profile" user.id %} ' method="POST" class="horizontal" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <p><input class="button" type="submit" value="Edit">

        </form>
</div>

{% endblock login %}

register/templates/login.html
{% extends 'base.html' %}

{% block login %}
<div class="large-offset-3 large-6 columns">

        <form action='{% url "auth:login"%}' method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {% if error %}
            <p><label class="error"><h2>{{ error }}</h2></label>
            {% endif %}
            <p><input class="button" type="submit" value="Log In">
            <button class="btn btn-info"><a href='{% url "auth:register"%}'>Register</a></button>

        </form>

</div>
{% endblock %}

register/templates/profile.html
{% extends 'base.html' %}


{% block content %}

    {% if user.profile.photo %}
    <img src='{{ user.profile.photo.url }}' class='img-responsive' width="300px" height="300px">
    {% endif %}
    <h3>Username : {{ user.username }}</h3>

    {% if user.first_name %}
    <h4>First name : {{ user.first_name}}</h4>
    {% endif %}

    {% if user.last_name %}
    <h4>Last name : {{ user.last_name}}</h4>
    {% endif %}

    {% if user.email %}
    <h4>Email : {{ user.email}}</h4>
    {% endif %}

    {% if user.profile.telephone %}
    <h4>Telephone : {{ user.profile.telephone}}</h4>
    {% endif %}

    {% if user.profile.country %}
    <h4>Country : {{ user.profile.country}}</h4>
    {% endif %}

    {% if user.profile.birth_date %}
    <h4>Date of birth : {{ user.profile.birth_date}}</h4>
    {% endif %}

    {% if user.date_joined %}
    <h4>On site since : {{ user.date_joined}}</h4>
    {% endif %}
      <h4><a href='{% url "post:user_post_list" user.id %} '>Posts</a>
    <br>
    <a href='{% url "post:user_comments_list" user.id%}'> Comments</a> </h4>
    <hr>

    {% if can_edit %}

<p> <button type="button" class="btn btn-default" value="Edit"><a href="{% url 'auth:edit_profile' user.id %}">Edit Profile</a> </button></p>

    {% endif %}
{% endblock content %}

register/templates/register.html
{% extends 'base.html' %}

{% block login %}

<div class="form-group">
        <form action='{% url "auth:register"%}' method="POST" class="horizontal" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <p><input class="button" type="submit" value="register">

        </form>
</div>

{% endblock login %}